name: CI/CD
 
on: 
  push:
    branches: ['main']
 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'
 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mayurpawar3099/ping-app-github:latest
 
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Deploy to minikube
        run:
          kubectl apply -f deployment.yaml
 
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Test service URLs
        run: |
          kubectl get services
          kubectl get deployments
          kubectl get pods
 
          # minikube service ping-app-service --url
 
          url=$(minikube service ping-app-service --url)
 
          # curl $(minikube service ping-app-service --url)
          # curl $(minikube service ping-app-service --url)/ping
          # curl $(minikube service ping-app-service --url)/healthz
 
          curl $url
          curl $url/ping
          curl $url/healthz
          # minikube service list
          # minikube service example --url
          # echo "------------------opening the service------------------"
          # curl $(minikube service example --url)     
has context menu
Compose
